// File generated by the Firebase Flutter SDK
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these with YOUR actual Firebase web config
  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyDaeTOSeqek_A6O4lb9TBkoT5zpeS90-7s', // Get from Firebase Console
    appId:
        '1:824131407632:android:2fd3db055f37adb5941f95', // Get from Firebase Console
    messagingSenderId: '824131407632', // Get from Firebase Console
    projectId: 'together-we-can-5d6e9', // Get from Firebase Console
    authDomain:
        'together-we-can-5d6e9.firebaseapp.com', // Get from Firebase Console
    storageBucket: 'your-project-id.appspot.com', // Get from Firebase Console
  );

  // For Android (if you need it later)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABC123...',
    appId: '1:1234567890:android:abc123def456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  // For iOS (if you need it later)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABC123...',
    appId: '1:1234567890:ios:abc123def456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.disabilityVolunteerApp',
  );

  // For other platforms (optional)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABC123...',
    appId: '1:1234567890:macos:abc123def456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.disabilityVolunteerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABC123...',
    appId: '1:1234567890:windows:abc123def456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyABC123...',
    appId: '1:1234567890:linux:abc123def456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );
}
